//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dienthoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdonhang
    {
        public long madonhang { get; set; }
        public long masp { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<decimal> dongia { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
